export const Disclamer =() =>{
   return <div className = 'disclamer'><span id='emphasis'>IMPORTANT!</span> THIS DATA IS TO BE USED AS REFERENCE ONLY AND IS NO SUBSTITUTE FOR SKILL, EXPERIENCE AND PROPER EDUCATION. SPATIAL ACCURACY OF THIS TYPE OF DATA IS VARIABLE AND SNOW PROFILES CHANGE DAY TO DAY. I AM NOT RESPONSIBLE FOR ANY INJURY, ACCIDENT, OR DEATH AS A RESULT OF USING THIS DATA. </div>

}